# Generated by Django 4.0.3 on 2022-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='images/profiles/default_profile.webp', upload_to='images/profiles'),
        ),
    ]
