# Generated by Django 4.0.3 on 2022-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='profiles/default_profile.webp', upload_to='profiles'),
        ),
    ]
